config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "gears#index"
  resources :users, only: [:show]
  resources :bookings, except: :new
  resources :gears do
    resources :bookings, only: [:new, :create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :gear
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :brand, :model, :size, :rate_per_day, :title, :description, :category ],
    associated_against: {
      bookings: [ :rental_start_date, :rental_end_date ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :gears
  has_one_attached :photo
  # validates :first_name, :last_name, :address, :email, :phone, presence: true
  # validates :email, format: { with: /@/ }, uniqueness: true
  # validates :phone, format: { with: /\d+/}
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end
  include Pagy::Backend
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_gear, only: [:new, :create]


  def new
    @booking = Booking.new
    @gears = Gear.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.gear = @gear
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(@booking.user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_gear
    @gear = Gear.find(params[:gear_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:rental_start_date, :rental_end_date)
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_gear, only: [:edit, :update, :destroy]

  def index
    @gears = Gear.all
    @markers = @gears.geocoded.map do |gear|
        {
          lat: gear.latitude,
          lng: gear.longitude
        }
      end
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR description ILIKE :query OR brand ILIKE :query OR model ILIKE :query OR size ILIKE :query OR category ILIKE :query"
      # @pagy, @gears = pagy(Gear.where(sql_subquery, query: "%#{params[:query]}%"))
      @gears = Gear.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @gears = Gear.all
      # @pagy, @gears = pagy(Gear.all, items: 5)
    end

  end

  def show
    @gear = Gear.find(params[:id])
    @booking = Booking.new
    @marker = {
      lat: @gear.latitude,
      lng: @gear.longitude
    }
  end
  def new
    @gear = Gear.new
  end

  def create
    @gear = Gear.new(gears_params)
    @gear.user_id = current_user.id
    @gear.save
    if @gear.save
      redirect_to gear_path(@gear), notice: "Gear was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @gear.update(gears_params)
    redirect_to gears_path(@gear)
  end

  def edit
  end

  def destroy
    @gear.destroy
    redirect_to gears_path
  end


  private

  def gears_params
    params.require(:gear).permit(:model, :brand, :size, :rate_per_day, :title, :category, :description, photos:[])
  end

  def set_gear
    @gear = Gear.find(params[:gear_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def home
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = @user.bookings
    @gears = @user.gears
  end

  private

  def article_params
    params.require(:user).permit(:first_name, :last_name, :body, :photo, :email, :address, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/bookings/_booking_form.html.erb
<%= simple_form_for [@gear, @booking] do |f| %>
  <%= f.input :rental_start_date %>
  <%= f.input :rental_end_date %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <%= render "booking_form" %>
</div>

app/views/gears/_gear_form.html.erb
<%= simple_form_for @gear do |f| %>
  <%= f.input :title, required: true, placeholder: "Enter item's title"%>
  <%= f.input :description, required: true, placeholder: "Enter item's description"%>
  <%= f.input :address, required: true, placeholder: "Where are you located?"%>
  <%= f.input :model, required: true, placeholder: "Enter item's model"  %>
  <%= f.input :brand, required: true, placeholder: "Enter item's brand"%>
  <%= f.input :category, collection: [ "Longboard", "Foamboard","Fish", "SUPboard", "Shortboard", "Bodyboard", "Wetsuit"]%>
  <%= f.input :size, required: false, placeholder: "(optional) Enter item's size"  %>
  <%= f.input :rate_per_day, required: true %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, "Create Gear Listing!", class:"btn btn-outline-success mb-3 shadow p-3  bg-body-tertiary rounded " %>
<% end %>

app/views/gears/create.html.erb
<h1>Gears#create</h1>
<p>Find me in app/views/gears/create.html.erb</p>

app/views/gears/destroy.html.erb
<h1>Gears#destroy</h1>
<p>Find me in app/views/gears/destroy.html.erb</p>

app/views/gears/edit.html.erb
<h1>Gears#edit</h1>
<p>Find me in app/views/gears/edit.html.erb</p>

app/views/gears/index.html copy.erb
<div class="container d-flex align-items-center justify-content-between">
  <div class="row row-4 mb-3">
    <% @gears.each do |gear| %>
      <div class='col-3 mx-3 mb-3 card'>
        <div class="card" style="width: 18rem;">
        <img src="<%= asset_path('1.png') %>" class="card-img-top" alt="...">
        <div class="card-body">
        <h2><%= link_to gear.model, gear_path(gear) %></h2>
        </div>
      </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Create a new Gear Listing", new_gear_path, class: "btn btn-primary" %>
</div>


<div class="cards-container bg-colour">
  <div class="cards">
    <% @gears.each do |gear| %>
      <div class="card-gear">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
          <%# <%= image_tag Faker::LoremFlickr.image%>
          <%# <img src="<%=Faker::LoremFlickr.image%>
        <div class="card-gear-infos">
          <div>
            <h2><%= link_to gear.title, gear_path(gear) %></h2>
            <p><%= gear.description%></p>
          </div>
          <h2 class="card-gear-pricing">£99.99</h2>
          <img src="<%=Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    <% end %>
  </div>
  <div id="pagination">
    <%# <%= render 'shared/pagination', pagy:@pagy %>
  </div>
  <%= link_to "Create a new Gear Listing", new_gear_path, class: "btn btn-primary" %>
</div>


<div class="cards-container bg-colour">
  <div class="cards">
    <% @gears.each do |gear| %>
      <div class="card-gear">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
          <%# <%= image_tag Faker::LoremFlickr.image%>
          <%# <img src="<%=Faker::LoremFlickr.image%>
        <div class="card-gear-infos">
          <div>
            <h2><%= link_to gear.title, gear_path(gear) %></h2>
            <p><%= gear.description%></p>
          </div>
          <h2 class="card-gear-pricing">£99.99</h2>
          <img src="<%=Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    <% end %>
  </div>


   <div id="pagination">
    <%# <%= render 'shared/pagination', pagy:@pagy %>
  </div>
  <%= link_to "Create a new Gear Listing", new_gear_path, class: "btn btn-primary" %>
</div>

<%= image_tag("logo.png", height: 400, width: 400, style: "border-radius: 50%;") %>

app/views/gears/index.html.erb
<div class="container-index bg-colour">
  <p class="display-1 white">Welcome to <span class="display-1"> WaveRent!<span></p>
  <h3>The place for <span id="yellow">you</span> to <span id="yellow">hire</span> <span id="blue">surf gear</span> <span></h3>
</div>

<div class="container bg-colour">
  <h4 class="h4-gear">Gear close to you</h4>
</div>
<div class="map">
  <div style="width: 40%; height: 560px; align-items: center; justify-content: center; box-shadow: 16px 16px 0px rgba(210, 238, 246, 0.4);"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>


<div class="container">
    <div class="row row-cols-4">
      <% @gears.each do |gear| %>
        <div class="col">
          <div class="card my-4 shadow " style="width: 18rem;, height: 20rem;">
            <div id="carousel<%= gear.id %>" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% gear.photos.each_with_index do |photo, i| %>
                  <div class="shadow carousel-item <%= 'active' if i == 0 %>">
                    <%= image_tag photo.url, class: 'd-block w-100', alt: "Gear Photo" %>
                  </div>
                <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel<%= gear.id %>" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel<%= gear.id %>" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </a>
            </div>
            <a href="/gears/<%= gear.id %>" class="card-link text-decoration-none">
              <div class="card-body ">
                <h5 class="card-title"><%= gear.title %></h5>
                <p class="card-text"><%= gear.description %></p>
                <hr>
              <ul class=" list-group list-group-horizontal justify-content-end rounded">
                <li class="list-group-item shadow-sm p-1 mb-2 me-2 ms-2 bg-body-tertiary rounded "><i class="fa-solid fa-dollar-sign"></i><%= gear.rate_per_day %></li>
              </ul>
                <a href="/gears/<%= gear.id %>" class="btn btn-outline-primary rounded">Info</a>
              </div>
            </a>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<div class="carousel-index">
  <%= render 'shared/carousel' %>
</div>


<% #below is the map html, @frontend: feel free to move this where fit,it is just slammed there all ugly for now %>

app/views/gears/nathan_index.html copy.erb
<<<<<<< HEAD:app/views/gears/index.html.erb
<%= render 'shared/carousel' %>
<div class="container">
  <p class="display-1">Welcome to WaveRent!</p>
  <h3 class="text-center">A place for you to hire surf gear</h3>
  <div class="bg-logo d-flex justify-content-center">
  <%= image_tag("logo.png", height: 400, width: 400, style: "border-radius: 50%;") %>
=======

<div class="container-index bg-colour">
  <%# <p class="display-1">Welcome to WaveRent!</p>
   <h3>A place for you to hire surf gear</h3> %>
>>>>>>> master:app/views/gears/nathan_index.html copy.erb
</div>
<div class="container">
  <h2 class="text-center my-2">Fresh boards near you 🏄‍♂️ </h2>
</div>
  <div class="container">
    <div class="row row-cols-4">
      <% @gears.each do |gear| %>
        <div class="col">
          <div class="card my-4 shadow " style="width: 18rem;, height: 20rem;">
            <div id="carousel<%= gear.id %>" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% gear.photos.each_with_index do |photo, i| %>
                  <div class="shadow carousel-item <%= 'active' if i == 0 %>">
                    <%= image_tag photo.url, class: 'd-block w-100', alt: "Gear Photo" %>
                  </div>
                <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel<%= gear.id %>" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel<%= gear.id %>" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </a>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= gear.title %></h5>
              <p class="card-text"><%= gear.description %></p>
              <hr>
            <ul class=" list-group list-group-horizontal justify-content-end rounded">
              <li class="list-group-item shadow-sm p-1 mb-2 me-2 ms-2 bg-body-tertiary rounded "><i class="fa-solid fa-dollar-sign"></i><%= gear.rate_per_day %></li>
            </ul>
              <a href="/gears/<%= gear.id %>" class="btn btn-outline-primary rounded">Rent Now</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>


  <div style="width: 50%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

app/views/gears/nathan_new.html.erb
<div class="container card my-4 shadow p-3 mb-5 bg-body-tertiary rounded">
  <%= render "gear_form" %>
</div>

app/views/gears/nathan_show.html.erb
<div class="d-flex container">
  <div class="row row-cols-2">
    <div id="carousel<%= @gear.id %>" class=" ms-2 carousel slide col-11" data-bs-ride="carousel" style="max-width: 900px; max-height: 80%;">
      <div class="carousel-inner card shadow">
        <% @gear.photos.each_with_index do |photo, i| %>
          <div class="shadow carousel-item <%= 'active' if i == 0 %>">
            <%= image_tag photo.url, class: 'd-block w-100', alt: "Gear Photo" %>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel<%= @gear.id %>" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel<%= @gear.id %>" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
  </div>
  <div class="card my-4 shadow col-3" style=" height: 30rem;">
    <div class="card-body justify-content-end">
      <h5 class="card-title"><%= @gear.title %></h5>
      <p class="card-text"><%= @gear.description %></p>
      <hr>
      <ul class=" list-group list-group-horizontal justify-content-end rounded">
        <li class="list-group-item shadow-sm p-1 mb-2 me-2 ms-2 bg-body-tertiary rounded "><i class="fa-solid fa-dollar-sign"></i><%= @gear.rate_per_day %></li>
      </ul>
      </div>
    </div>
</div>


<div class="container relative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card shadow-lg p-3 mb-3 bg-body-tertiary rounded">
        <h2><%= @gear.title %></h2>
        <p><%= @gear.brand %></p>
      </div>
      <div class="flat-show-card shadow-lg p-3 mb-3 bg-body-tertiary rounded">
        <h3>A bit more about this <%= @gear.category %>...</h3>
        <p><%= @gear.model %></p>

        <div class="map">
      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
              </div>
      </div>
    </div>
    <div id="sticky" class="col-4 py-3 ">
      <form class="card shadow-lg p-3 mb-3 bg-body-tertiary rounded" action="/book" method="POST">
  <div class="card mb-3">
    <label class="form-label" for="from-date">From:</label>
    <input class="form-control" type="date" id="from-date" name="from-date" required>
  </div>
  <div class="card mb-3">
    <label class="form-label" for="to-date">To:</label>
    <input class="form-control" type="date" id="to-date" name="to-date" required>
  </div>
  <button class="btn btn-primary" type="submit">Book now!</button>
</form>


    <div class="flat-show-card shadow-lg p-3 mb-3 bg-body-tertiary rounded">
      <div class="flex">
        <h4>Recommend to a friend!</h4>
        <a href=""><i class="fa-brands fa-facebook"></i></a>
        <a href=""><i class="fa-brands fa-twitter"></i></a>
        <a href=""><i class="fa-brands fa-square-pinterest"></i></a>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/gears/new.html.erb
<div class="container card my-4 shadow p-3 mb-5 bg-body-tertiary rounded">
  <%= render "gear_form" %>
</div>

app/views/gears/update.html.erb
<h1>Gears#update</h1>
<p>Find me in app/views/gears/update.html.erb</p>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaveRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bowlby+One+SC&family=Dongle:wght@300;400;700&family=Orelega+One&display=swap" rel="stylesheet">
    <link href="app/assets/stylesheets/application.scss" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    </head>

  <body>
    <%= render 'shared/flashes' %>
  <div class="sticky-top navbar-design">
    <%= render 'shared/navbar' %>
  </div>
    <% if user_signed_in? %>
        <% if current_user.photo.present? %>
          <%= cl_image_tag current_user.photo.key, height: 50, width: 50, crop: :fill ,style: "border-radius: 50%;"%>
        <% else %>
          <%= cl_image_tag "twh96ztaabtvaahrq8t1", height: 100, width: 100, crop: :fill ,style: "border-radius: 50%;"%>
        <% end %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaveRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bowlby+One+SC&family=Dongle:wght@300;400;700&family=Orelega+One&display=swap" rel="stylesheet">
    <link href="app/assets/stylesheets/application.scss" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    </head>

  <body>
    <%= render 'shared/flashes' %>
  <div class="sticky-top navbar-design">
    <%= render 'shared/navbar' %>
  </div>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

  <%= link_to "Surf gears", new_user_session_path, class:"btn btn-primary" %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
        <p class="display-3">WaveRent</p>
    <% end %>
      <div class="container-fluid search">
        <%= form_with url: gears_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for Gear"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Rent Your Gear!", new_gear_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <div class="container-avatar" id="navbarDropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" aria-current="page" href="/users/<%= current_user.id %>">Dashboard</a>
              <%= link_to "My Gear", "#", class: "dropdown-item " %>
              <%= link_to "My Bookings", "#", class: "dropdown-item " %>
              <%= link_to "Account Settings", "#", class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path,data: {turbo_method: :delete}, class:"qms-5 qbtn qbtn-primary dropdown-item signout" %>
            </div>
              <h4 ><%= current_user.email.to_s.split('@')[0] %></h4>
            </div>

          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_old_navbar.html.erb
<nav class="card bg-white navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid mb-2 mt-2">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-lg-0">
       <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><i class="fas fa-water me-1 text-secondary"></i>WaveRent</a>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users/<%= current_user.id %>">Dashboard</a>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Surf Gear
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Boards</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Uniforms</a></li>
          </ul>
        </li>
      </ul>
        <% if current_user %>
          <%= link_to "New Gear", new_gear_path, class:"me-5 btn btn-success" %>
        <% end %>
        <div class="col-sm-8 my-3">
          <%= form_with url: gears_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search for Gear"
              %>
            <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
          <% end %>
        </div>
        <% if current_user %>
        <%= link_to "Sign out", destroy_user_session_path,data: {turbo_method: :delete}, class:"ms-5 btn btn-primary" %>
        <% end %>
      </ul>
    </div>
  </div>

app/views/shared/angelos_comps.html.erb
<nav class="navbar navbar-expand-lg shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<a class="nav-link active" aria-current="page" href="/">
  <%= image_tag("logo.png", height: 100, width: 100,style: "border-radius: 50%;") %>
</a>      <div class="col-sm-8 my-3">
        <%= form_with url: gears_path, method: :get, class: "justify-content-end px-5 d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "px-4",
                placeholder: "Search for Gear"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <a class="nav-link active" aria-current="page" href="/users/<%= current_user.id %>">
      <% if current_user.photo.present? %>
        <div class="d-flex">
          <div class="dropdown">
            <span><%= cl_image_tag current_user.photo.key, height: 50, width: 50, crop: :fill ,style: "border-radius: 50%;", class: "shadow  bg-body-tertiary me-3"%>
            </span>
            <div class="dropdown-content">
              <%= link_to "Add Gear", new_gear_path, class:"text-decoration-none link-body-emphasis" %>
              <hr>
              <%= link_to "Sign out", destroy_user_session_path,data: {turbo_method: :delete}, class:"text-decoration-none link-body-emphasis" %>
            </div>
          </div>
          </div>
          <p class="d-flex"><%= current_user.email %></p>
      <%else%>
          <div class="d-flex">
        <%= cl_image_tag "twh96ztaabtvaahrq8t1", height: 100, width: 100, crop: :fill ,style: "border-radius: 50%;", class: "shadow  bg-body-tertiary me-3"%>
        </div>
      <% end %>
    <% end %>
  </div>
</nav>